customhost = "database-1.cdsilkd4knvu.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "gweeyongsean-bucket"
customregion = "us-east-1"
